name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '25'
        cache: 'npm'
        cache-dependency-path: './package-lock.json'

    - name: Get the public IP of the runner
      id: get-ip
      shell: bash
      run: |
        echo "curl https://ipinfo.io/ip >> "$GITHUB_OUTPUT"

    - name: Install dependencies
      run: npm install

    - name: Run JSDoc to verify documentation build
      run: npm run doc

    # Exemple d'exécution de tests avec les variables d'environnement
    - name: Run tests
      run: npx mocha tests/*.test.js
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        URL_MONGO: ${{ secrets.URL_MONGO }}
